# Generated by Django 6.0.3 on 2026-03-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='holiday',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
