# Generated by Django 6.0.3 on 2026-03-31 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_alter_holiday_options_rename_date_holiday_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={},
        ),
    ]
